version: "3.8"
services:
  backend:
    build:
      context: ./services/backend/
      dockerfile: ./build/Dockerfile
      target: build
    ports:
      - 8080:8080
    volumes:
      - ./services/backend/:/app
    restart: on-failure
    command: air -c .air.toml
    networks:
      - ws_chat
  frontend:
    build:
      context: ./services/frontend/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      REACT_APP_WS_SERVICE: ws://localhost:8080
    volumes:
      - ./services/frontend/:/app
    restart: on-failure
    networks:
      - ws_chat
networks:
  ws_chat:
